#!/bin/bash

# To check if user is running on sudo
if [[ ! $EUID == 0 ]]; then
    echo "$0 is not running as root. Please use sudo."
    exit 1
fi

# Create user webgen with home directory at /var/lib/webgen
useradd -r -m -d /var/lib/webgen -s /usr/bin/nologin webgen 

# Create /bin and /HTML directories
mkdir -p /var/lib/webgen/bin 
mkdir -p /var/lib/webgen/HTML

# Ensure user webgen has ownership of the directories
chown -R webgen /var/lib/webgen

# Create systemd service
cat <<EOL | sudo tee /etc/systemd/system/generate-index.service
[Unit]
Description=Generate index.html
After=network-online.target
Wants=network-online.target

[Service]
User=webgen
Group=webgen
ExecStart=/var/lib/webgen/bin/generate_index

[Install]
WantedBy=multi-user.target
EOL

# Create systemd timer
cat <<EOL | sudo tee /etc/systemd/system/generate-index.timer
[Unit]
Description=Run generate-index.service daily at 05:00

[Timer]
OnCalendar=*-*-* 05:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOL

cat <<EOL | sudo tee /etc/nginx/sites-available/webgen
server {
    listen 80;
    server_name _;

    root /var/lib/webgen/HTML;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

